ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - tsx@4.22.5
shellEmulator: true
trustPolicy: no-downgrade
allowBuilds:
  esbuild: true
  simple-git-hooks: true
packages:
  - playground
  - examples/*
